# Minimal configuration for GitHub Pages
title: Helix Toolkit
description: '3D Graphics for .NET'
url: https://helix-toolkit.github.io/

# Links
helix-toolkit: https://helix-toolkit.github.io/helix-toolkit/
helix-toolkit-nex: https://helix-toolkit.github.io/helix-toolkit-nex/
